version: '3.9'

volumes:
  postgres_data: { }

x-app-as-service: &app_as_service
  build: .
  environment:
    - POSTGRES_HOST=postgres
    - POSTGRES_PORT=5432
    - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672/
  env_file:
    - .env
  depends_on:
    - postgres
  profiles:
    - outside_dev

services:
  app:
    <<: *app_as_service
    command: /start.sh

  postgres:
    image: postgres:15.4
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data:rw
    profiles:
      - outside_dev
      - local_dev

  rabbitmq:
    image: rabbitmq:3.11.4-management-alpine
    profiles:
      - outside_dev
      - local_dev

  celery-worker:
    <<: *app_as_service
    command: /celery_worker_start.sh

  celery-beat:
    <<: *app_as_service
    command: /celery_beat_start.sh